#!/bin/bash
for i in {0..12}
do
for j in {1..3}
do
cp job_dft.slm job_dft_$i.$j.slm
perl -pi -e "s/i=-1/i=$i/" job_dft_$i.$j.slm
if [ $j -eq 2 ]
then
	perl -pi -e "s/j in {0..5}/j in {6..11}/" job_dft_$i.$j.slm
fi
if [ $j -eq 3 ]
then
        perl -pi -e "s/j in {0..5}/j in {12..16}/" job_dft_$i.$j.slm
fi
perl -pi -e "s/num/num_$i.$j/" job_dft_$i.$j.slm
done
done

